name: Update RSS

on:
  schedule:
    - cron: "0 * * * *"   # every 1 hr
  workflow_dispatch:         # manual trigger button

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scrapers
        run: |
          python idrw_scraper.py
          python cbi_scraper.py

      - name: Commit xml files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -f *.xml
          git commit -m "Update RSS" || echo "No changes"
          git push
